version: '3.8'
services:
  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=portfolio
      - MYSQL_USER=tony
      - MYSQL_PASSWORD=1234
    ports:
      - 3307:3306
    volumes:
      - wp:/var/lib/mysql
volumes:
  wp: